- id: ruff
  name: ruff
  description: "Run 'ruff' for extremely fast Python linting"
  entry: ruff check --force-exclude
  language: python
  types_or: [python, pyi, jupyter]
  require_serial: true
  additional_dependencies:
    - ruff==0.4.7

- id: format
  name: format
  description: "Run custom formatting"
  entry: format
  language: python
  types_or: [python, pyi, jupyter]
  require_serial: true
  additional_dependencies:
    - ruff==0.4.7
