default_language_version:
  python: python3

default_stages: [commit, manual]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
      - id: identity
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", main]
        stages: [commit]
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml

  - repo: https://github.com/crate-ci/typos
    rev: v1.14.3
    hooks:
      - id: typos

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.0
    hooks:
      - id: toml-sort
        args:
          - --in-place
          - --trailing-comma-inline-array
          - --spaces-before-inline-comment=2

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-clean-block==0.1.2
        args: ["--ignore=E,F,W,C90"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: [--trailing-comma, all]
