default_language_version:
  python: python3

default_stages: [commit, manual]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
      - id: identity
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", main]
        stages: [commit]
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-dependabot
      - id: check-github-workflows

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.8
    hooks:
      - id: typos

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place
          - --trailing-comma-inline-array
          - --spaces-before-inline-comment=2
          - --all

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
      - id: auto-walrus

  - repo: https://github.com/Core-Power-UK/format
    rev: v23.8.1
    hooks:
      - id: format

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-clean-block==0.1.2
        args: ["--ignore=E,F,W,C90"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--config-file, pyproject.toml]
        additional_dependencies:
          - add-trailing-comma==3.0.0
          - black==23.7.0
          - types-requests==2.31.0.2

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        args: [--trailing-comma, all]
        exclude_types: [json]
