default_language_version:
  python: python3.11

default_stages: [commit, manual]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", main]
        stages: [commit]
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: file-contents-sorter
        files: ".cspell/dict.txt"
        args: [--ignore-case]
      - id: file-contents-sorter
        files: ".cspell/config_dict.txt"
        args: [--ignore-case]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows

  - repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
      - id: typos

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.12.1
    hooks:
      - id: markdownlint-cli2
        args: [--fix]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.6.0
    hooks:
      - id: cspell
        additional_dependencies:
          - "@cspell/dict-python"
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place
          - --trailing-comma-inline-array
          - --spaces-before-inline-comment=2
          - --all

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-clean-block==0.1.2
        args: ["--ignore=E,F,W,C90"]

  - repo: https://github.com/Core-Power-UK/format
    rev: v24.03.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--config-file, pyproject.toml]
        additional_dependencies:
          - packaging==24.0
          - types-requests==2.31.0.20240311

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--trailing-comma, all]
        exclude_types: [json, python]
        exclude: |
          (?x)(
              ^.*\.jsonc
          )
