name: Update caches

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  cache-standard-checks:
    name: Cache standard checks dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11

      - name: Pip Cache
        uses: actions/cache@v4.0.2
        id: python_cache
        with:
          path: |
            env
          key: env-${{ steps.setup_python.outputs.python-version }}-lint-${{ hashFiles('requirements/lint.txt') }}

      - name: Cache Pre-commit
        uses: actions/cache@v4.0.2
        id: pre_commit_cache
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install linting dependencies
        if: ${{ steps.python_cache.outputs.cache-hit != 'true' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv env
          env/bin/python -m pip install -r requirements/lint.txt

      - name: Install pre-commit hooks
        if: ${{ steps.pre_commit_cache.outputs.cache-hit != 'true' }}
        env:
          PRE_COMMIT_COLOR: always
        run: env/bin/python -m pre_commit install --install-hooks
