name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 1 * *"

jobs:
  auto-update:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11

      - name: Install requirements
        run: |
          python -m pip install requests==2.31.0
          python -m pip install packaging==24.0

      - name: Update dependencies
        run: |
          python scripts/update_dependencies.py

      - name: Generate token
        id: generate_token
        env:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ env.app_id }}
          private_key: ${{ env.app_private_key }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.5
        with:
          branch: update/dependencies
          title: Update dependencies
          commit-message: Update dependencies
          body: Bump versions of format dependencies to latest version
          labels: Dependency Update
          token: ${{ steps.generate_token.outputs.token }}
          assignees: calumy
